spring.application.name=saber-pro-web
# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS H2
# ===============================
# Cambia 'mem' por 'file' y define una ruta (./data/saberpro)
spring.datasource.url=jdbc:h2:file:./data/saberpro
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

# Habilitar la consola web de H2 (Se accederá desde http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Cambia 'mem' por 'file' y define una ruta (./data/saberpro)
# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Actualiza el esquema de la base de datos automáticamente cada vez que corras el proyecto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# ===============================
# CONFIGURACIÓN DE THYMELEAF
# ===============================
# Desactivar la caché en desarrollo para ver los cambios de HTML al instante
spring.thymeleaf.cache=false